### PR TITLE
Add run on repl.it badge to README

### PR DESCRIPTION
**Pull request by amasad**
Hey @klange I see you setup the repo -- why not add the badge? ;)

### CODE REVIEW

**Comment by BetiDev** [comment]
this can work on repl.it?

**Comment by klange** [comment]
@BetiDev There are a couple of issues with the terminal emulator used by repl.it that I noticed while testing bim, but I was quite happily surprised to find that most things work pretty well with it.

@amasad Is the terminal emulator a repl.it project or something third party? I would like to report these issues the appropriate place.

1. The terminal occasionally corrupts output, possibly dropping or swapping bytes, which can break the display; note line 37 where one of the midline dots used to indicate a tab has been displayed instead as two replacement characters:

Screenshot from 2019-12-14 11-09-03

2. In Firefox (on Linux), the terminal sends the same escape sequences in mouse modes when scrolling up and down (specifically the button code for down). Chrome did not present this issue. This is especially interesting to me because the default vim config sets a mode which has the mouse produce up/down arrow events, and those send the correct direction, so the terminal emulator is correctly getting different input on scroll up or scroll down, but is doing something wrong with them that is browser-dependent when converting them to mouse event escape sequences.

3. Screen scrolling works when scrolling down, but not always when scrolling up (dependent on the number of lines, possibly the cursor position relative to the top of the screen?). Vim manages to avoid this issue because it uses `^[[L` to insert lines rather than scrolling up, and I've confirmed that doing that fixes bim as well, but still find this one interesting.

**Comment by amasad** [comment]
@klange we use xterm.js which is used by vscode and others. If you can reproduce it easily it might be worth sending a bug report there.

@turbio do you think any of these bugs are repl.it-specific?

**Comment by klange** [comment]
Hello, I am revisiting repl.it as an option for providing a web-based playground for trying Bim. It seems some features have changed in the terminal support on repl.it in the last year; I no longer get mouse events, and the build container doesn't seem to be getting the actual terminal size so termios reports a fixed 80x24. I am also still seeing dropped bytes between the container output and the web terminal.

If it's become problematic to pass the terminal size information to the container, I have a workaround:

```bash
#!/bin/bash
stty -echo
P=$(echo -n -e "\033[s\033[1000;1000H\033[6n\033[u")
read -p "${P}" -t 0.2 -d R
H=$(echo ${REPLY:2} | sed s'/\;.*//')
W=$(echo ${REPLY:2} | sed s'/.*\;//')
stty cols $W rows $H
stty echo
```

**Pull request closed without merging**
