### PR TITLE
Makefile: added clean, install, uninstall rules

### PR DESCRIPTION
**Pull request by x4m3**
let me know if i did something wrong.

### CODE REVIEW

**Comment by tay10r** [comment]
How about using `$(RM)` instead of `rm`

**Comment by tay10r** [comment]
Not my project, so up the maintainer to merge.

I would also consider renaming your `DESTDIR` variable.
I may be nit picking at this point, since it's just a small file.

`DESTDIR` is usually for staging installs, not actual installs.

I would use a combination of:

  - `prefix`
  - `bindir`
  - `DESTDIR`

The `prefix` variable should default to `/usr/local`.
The `bindir` variable should default to `$(prefix)/bin`

The `DESTDIR` variable should be used in the Makefile like this:

```makefile
install:
  cp $(TARGET) "$(DESTDIR)$(bindir)"

uninstall:
  $(RM) "$(DESTDIR)$(bindir)"/$(TARGET)
```

References:
  - https://www.gnu.org/prep/standards/html_node/Directory-Variables.html#Directory-Variables
  - https://www.gnu.org/prep/standards/html_node/DESTDIR.html#DESTDIR

**Comment by klange** [comment]
"Compliant" Makefiles are tricky things.

- `rm` should be called directly; it is in a list of safe commands, alongside things like `cp` and `mkdir`.
- Installation should be done with `install` which should be referenced as `INSTALL` or `INSTALL_PROGRAM`.
- `prefix`, `exec_prefix`, `bindir`, `DESTDIR` are expected in normal usage.

I have replaced the stub Makefile with one better suited for deployment and am closing this pull request.

**Comment by x4m3** [comment]
no problem, at least i learnt some stuff about makefiles.

but is all this stuff really necessary ? the basic makefile was working just fine....

**Comment by klange** [comment]
If the project is picked up by a package maintainer for a Linux or BSD distribution, then the extended Makefile will better serve their efforts in creating packages.

**Pull request closed without merging**
